### ISSUE TITLE
Criar view Clinical history

### ISSUE THREAD

**Issue by william-ribeiro** [william-ribeiro/api-healthy-mind#58]
GET /sessions/{**patientId**}

{
  "response": [
    {
      "id": 2,
      "createdAt": "2022-09-21T00:40:48.961Z",
      "updatedAt": "2022-09-21T00:40:48.961Z",
      "patientId": "{**patientId**}",
      "status": "agendada",
      "subject": "ASD",
      "duration": "2022-09-20T03:02:00.036Z",
      "type": "individual",
      "enabled": true,
      "appointmentDate": "2022-09-21T03:00:00.000Z",
      "service": "remote",
     }
   ]
}

OBS.: Ordenado por _updatedAt_. Filtrar por _status_ = _closed_

**Comment by adlermo** [comment]
STATUS de Sessão:

OPEN,
CLOSED,
CANCELED
