### ISSUE TITLE
[Fix] - Atualizar paciente não deve requerer a alteração de senha sempre

### ISSUE THREAD

**Issue by adlermo** [william-ribeiro/api-healthy-mind#85]
**Ajuste 1:**

É necessário ajustar a resposta do endpoint *`POST /signin?type=patient`* 
`
{
   "message": "Password must be changed",
   "token": ""
}
`

Para trazer o id do usuário
`
{
   "message": "Password must be changed",
   "token": "",
   "id": "f0b5bc18-4fec-4ca1-a950-db1be8c309cf",
   "roleId": 2,
}
`

Que será necessário para alterar a senha em:

`PUT /patients/update/{patientId}`

**Ajuste 2:**
Permitir que `PUT /patients/update/{patientId}` não necessite alterar a senha uma primeira vez para alterar os dados do usuário.

Verificar erro `{"message":"No entity column \"patientId\" was found.","token":null}`

**Comment by william-ribeiro** [comment]
@adlermo  

- [V ]  **Ajuste 1**, já foi coberto na feature do @luciano-ilha , você testou a partir dela?

- [V ] **Ajuste 2**,  eu não posso deixar ele acessar sem trocar a senha, mas foi validador para o professional conseguir alterar os dados, caso cadastre algo errado.

**Comment by adlermo** [comment]
@william-ribeiro 

1. Sim, eu testei a partir da feature do @luciano-ilha, justamente lá ele não tem o patientId pra mandar (e está mandando uma string vazia), pq a resposta de /signin retorna apenas token, sem id do usuário paciente

2. Eu testei alterar justamente pelo profissional, é lá que dá a mensagem de primeiro alterar a senha

**Comment by william-ribeiro** [comment]
1. Exatamente esse o comportamento, ele joga a string vazia, o back valida essa condição e injeta o id do paciente. Testamos na branch , todo comportamento de login e. Alteração de senha e funcionou.

2. Boa, então agora vc já deve conseguir, fiz esse ajuste
